# Generated by Django 4.2.4 on 2023-09-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='clock_count',
            new_name='count',
        ),
    ]
