# Generated by Django 4.2.4 on 2023-09-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_rename_clock_count_reservation_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='count',
            new_name='reserved_clocks_count',
        ),
    ]
