# Generated by Django 4.2.4 on 2023-09-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_rename_count_reservation_reserved_clocks_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_clocks_count',
            new_name='clock_count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='clock',
        ),
        migrations.AddField(
            model_name='reservation',
            name='clocks',
            field=models.ManyToManyField(related_name='reservations', to='reserve.rclock'),
        ),
    ]
