# Generated by Django 4.2.4 on 2023-09-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_rename_reserved_clocks_count_reservation_clock_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='clock_count',
        ),
    ]
