# Generated by Django 4.2.4 on 2023-09-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_studyroom_date_studyroom_time0_studyroom_time1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='rclock',
            field=models.ManyToManyField(blank=True, related_name='reservateclock', to='reserve.rclock'),
        ),
    ]
